apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard # name of the Minikube storage class
  accessModes:
    - ReadWriteOnce # For local hostPath, ReadWriteOnce is the only supported mode
  hostPath:
    path: /data
    type: DirectoryOrCreate
